In [1]:
import numpy as np
import pandas as pd
import rasters as rt

In [2]:
filename = "BESS/ball_berry_intercept_C3.tif"

In [3]:
df = pd.read_csv("calval_harvard.csv")
lat = df.lat
lon = df.lon

In [4]:
values = rt.Raster.read_at_lat_lon(filename, lat, lon)
values

array([0.005, 0.005, 0.005, ..., 0.005, 0.005, 0.005], dtype=float32)

In [5]:
np.unique(values)

array([0.005], dtype=float32)

In [6]:
coords = rt.CoordinateArray(lon, lat)
coords

In [7]:
values = rt.Raster.open(filename, geometry=coords)
values

array([0.005, 0.005, 0.005, ..., 0.005, 0.005, 0.005], dtype=float32)